#!/bin/bash
# This batch builds the C++ library, all C++ examples, and the Python library.
# You will need to install Cython
#		sudo yum install Cython
make all
python3 setup_pYqRand.py build_ext --build-lib=./lib
python2 setup_pYqRand.py build_ext --build-lib=./lib
